export const pages = {
  goToAfterLogin: 'teams',
  goToAfterRegister: 'confirm',
  goToNotAuthanticated: 'login',
  home: 'index',
  dashboard: 'dashboard',
  logout: 'logout',
  login: 'login',
  register: 'register',
  account: 'account',
  confirm: 'confirm',
  privacyPolicy: 'privacy-policy',
  termsOfUse: 'terms-of-use',
  teams: 'teams',
  teamsItem: 'teams-item',
  teamsCreate: 'teams-create',
  teamsEdit: 'teams-teamId-edit',
  apiKeys: 'teams-teamId-apiKeys',
  apiKeysItem: 'teams-teamId-apiKeys-id',
};
