### Get all users
GET http://localhost:3333/users

### Get one user
GET http://localhost:3333/users/1

### Create a User
POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "user@email.com",
    "password": "123456"
}

### Update a User
PUT http://localhost:3333/users/1
Content-Type: application/json

{
    "name": "John Doe2",
    "email": "user@email.com",
    "password": "123456"
}

### Delete a User
PUT http://localhost:3333/users/3