name: Api CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Build docker image
        run: docker build -t ${{ secrets.REPO_URL }}:cmx-api-${GITHUB_SHA::7} .
        working-directory: api

      - name: Run docker login
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 241533120616.dkr.ecr.us-east-1.amazonaws.com

      - name: Push image to repo
        run: docker push ${{ secrets.REPO_URL }}:cmx-api-${GITHUB_SHA::7}

  deploy:
    runs-on: self-hosted
    steps:
      - name: Setup git config and clone infra repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"
          git clone git@github.com:${{ secrets.HELM_REPO_URL }}.git
        working-directory: /tmp/

      - name: Update image tag
        run: |
          sed -i '/tag: cmx-api/d' ./helm/cmx-api/values.yaml
          echo "  tag: cmx-api-${GITHUB_SHA::7}" >> ./helm/cmx-api/values.yaml
        working-directory: /tmp/gitops

      - name: Commit and push image tag
        run: |
          export COMMIT_MESSAGE="Update API image tag: ${GITHUB_SHA::7}"
          git add ./helm/cmx-api/values.yaml
          git commit -m "$COMMIT_MESSAGE"
          git push
        working-directory: /tmp/gitops

      - name: Cleanup
        run: rm -rf gitops
        working-directory: /tmp/
